# Generated by Django 3.2.5 on 2021-07-07 14:14

from django.db import migrations, models
import vehicle_registry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(auto_created=True, max_length=3)),
                ('number', models.CharField(max_length=6, unique=True, validators=[vehicle_registry.models.validate_number])),
                ('maker', models.CharField(max_length=32)),
                ('manufacturing_date', models.DateField()),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
