# Postgres Container

version: '3.7'

services:

  db:
    container_name: pgdb
    image: postgres:12.9-bullseye
    # automatically restarts the container
    restart: always

    env_file: ./docker/postgres/docker-postgres.env

    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata

    networks:
      app_net:
        ipv4_address: "192.168.0.2"

volumes:
  postgres_data_dev:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"

