# Development Container

version: '3.1'

services:

  db:
    container_name: ${DB_CONTAINER}
    image: postgres:12.8-buster
    # automatically restarts the container
    restart: always

    volumes:
      - ${HOST_VOLUME}=${CONTAINER_VOLUME}

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      PGDATA: ${PGDATA}
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: ${PGADMIN_CONTAINER}
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 192.168.0.3
    networks:
      app_net:
        ipv4_address: 192.168.0.3

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/28"
